# Generated by Django 5.1.2 on 2024-11-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order_details'),
        ),
        migrations.CreateModel(
            name='return_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_return', models.TextField(max_length=1000)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.return_order')),
            ],
        ),
    ]
