# Generated by Django 5.1.2 on 2024-11-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_remove_custom_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
